# Site settings
title: "Saurabh Singh"
description: "About Saurabh"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Saurabh Singh"
resume_title:                   "Associate at Goldman Sachs"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "saurabhsingh0408@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "9916712709"
resume_contact_address:         "Bangalore, IN"

resume_header_contact_info:     "Bangalore, IN • 9916721709 • saurabhsingh0408@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>To work in a challenging environment demanding all my skills and efforts to explore and adapt myself in different fields and realize my potential where I get the opportunity for continuous learning.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display
resume_social_links:
  resume_github_url:            "https://github.com/saurabhsingh0408/about-me"
  resume_twitter_url:           "http://twitter.com/saurabh_0408"
  resume_facebook_url:          "https://www.facebook.com/saurabh.singh.0408"
  resume_linkedin_url:          "https://www.linkedin.com/in/saurabh-singh-a4916126/"
  resume_instagram_url:         "https://www.instagram.com/saurabh_0408/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
